/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize);
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte =
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize);
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if Self::raw_get_bit(this, i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            Self::raw_set_bit(this, index + bit_offset, val_bit_is_set);
        }
    }
}
pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C2X_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 39;
pub const _SYS_CDEFS_H: u32 = 1;
#[allow(non_upper_case_globals)]
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const IDXD_SCMD_SOFTERR_MASK: u32 = 2147483648;
pub const IDXD_SCMD_SOFTERR_SHIFT: u32 = 16;
pub const IDXD_OP_FLAG_FENCE: u32 = 1;
pub const IDXD_OP_FLAG_BOF: u32 = 2;
pub const IDXD_OP_FLAG_CRAV: u32 = 4;
pub const IDXD_OP_FLAG_RCR: u32 = 8;
pub const IDXD_OP_FLAG_RCI: u32 = 16;
pub const IDXD_OP_FLAG_CRSTS: u32 = 32;
pub const IDXD_OP_FLAG_CR: u32 = 128;
pub const IDXD_OP_FLAG_CC: u32 = 256;
pub const IDXD_OP_FLAG_ADDR1_TCS: u32 = 512;
pub const IDXD_OP_FLAG_ADDR2_TCS: u32 = 1024;
pub const IDXD_OP_FLAG_ADDR3_TCS: u32 = 2048;
pub const IDXD_OP_FLAG_CR_TCS: u32 = 4096;
pub const IDXD_OP_FLAG_STORD: u32 = 8192;
pub const IDXD_OP_FLAG_DRDBK: u32 = 16384;
pub const IDXD_OP_FLAG_DSTS: u32 = 32768;
pub const IDXD_OP_FLAG_RD_SRC2_AECS: u32 = 65536;
pub const IDXD_OP_FLAG_RD_SRC2_2ND: u32 = 131072;
pub const IDXD_OP_FLAG_WR_SRC2_AECS_COMP: u32 = 262144;
pub const IDXD_OP_FLAG_WR_SRC2_AECS_OVFL: u32 = 524288;
pub const IDXD_OP_FLAG_SRC2_STS: u32 = 1048576;
pub const IDXD_OP_FLAG_CRC_RFC3720: u32 = 2097152;
pub const DSA_COMP_STATUS_MASK: u32 = 127;
pub const DSA_COMP_STATUS_WRITE: u32 = 128;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub const IDXD_SCMD_DEV_ENABLED: idxd_scmd_stat = 2147483664;
pub const IDXD_SCMD_DEV_NOT_ENABLED: idxd_scmd_stat = 2147483680;
pub const IDXD_SCMD_WQ_ENABLED: idxd_scmd_stat = 2147483681;
pub const IDXD_SCMD_DEV_DMA_ERR: idxd_scmd_stat = 2147614720;
pub const IDXD_SCMD_WQ_NO_GRP: idxd_scmd_stat = 2147680256;
pub const IDXD_SCMD_WQ_NO_NAME: idxd_scmd_stat = 2147745792;
pub const IDXD_SCMD_WQ_NO_SVM: idxd_scmd_stat = 2147811328;
pub const IDXD_SCMD_WQ_NO_THRESH: idxd_scmd_stat = 2147876864;
pub const IDXD_SCMD_WQ_PORTAL_ERR: idxd_scmd_stat = 2147942400;
pub const IDXD_SCMD_WQ_RES_ALLOC_ERR: idxd_scmd_stat = 2148007936;
pub const IDXD_SCMD_PERCPU_ERR: idxd_scmd_stat = 2148073472;
pub const IDXD_SCMD_DMA_CHAN_ERR: idxd_scmd_stat = 2148139008;
pub const IDXD_SCMD_CDEV_ERR: idxd_scmd_stat = 2148204544;
pub const IDXD_SCMD_WQ_NO_SWQ_SUPPORT: idxd_scmd_stat = 2148270080;
pub const IDXD_SCMD_WQ_NONE_CONFIGURED: idxd_scmd_stat = 2148335616;
pub const IDXD_SCMD_WQ_NO_SIZE: idxd_scmd_stat = 2148401152;
pub const IDXD_SCMD_WQ_NO_PRIV: idxd_scmd_stat = 2148466688;
pub const IDXD_SCMD_WQ_IRQ_ERR: idxd_scmd_stat = 2148532224;
pub const IDXD_SCMD_WQ_USER_NO_IOMMU: idxd_scmd_stat = 2148597760;
pub const IDXD_SCMD_DEV_EVL_ERR: idxd_scmd_stat = 2148663296;
pub const IDXD_SCMD_WQ_NO_DRV_NAME: idxd_scmd_stat = 2149580800;
#[allow(non_camel_case_types)]
pub type idxd_scmd_stat = ::std::os::raw::c_uint;
pub const DSA_OPCODE_NOOP: dsa_opcode = 0;
pub const DSA_OPCODE_BATCH: dsa_opcode = 1;
pub const DSA_OPCODE_DRAIN: dsa_opcode = 2;
pub const DSA_OPCODE_MEMMOVE: dsa_opcode = 3;
pub const DSA_OPCODE_MEMFILL: dsa_opcode = 4;
pub const DSA_OPCODE_COMPARE: dsa_opcode = 5;
pub const DSA_OPCODE_COMPVAL: dsa_opcode = 6;
pub const DSA_OPCODE_CR_DELTA: dsa_opcode = 7;
pub const DSA_OPCODE_AP_DELTA: dsa_opcode = 8;
pub const DSA_OPCODE_DUALCAST: dsa_opcode = 9;
pub const DSA_OPCODE_TRANSL_FETCH: dsa_opcode = 10;
pub const DSA_OPCODE_CRCGEN: dsa_opcode = 16;
pub const DSA_OPCODE_COPY_CRC: dsa_opcode = 17;
pub const DSA_OPCODE_DIF_CHECK: dsa_opcode = 18;
pub const DSA_OPCODE_DIF_INS: dsa_opcode = 19;
pub const DSA_OPCODE_DIF_STRP: dsa_opcode = 20;
pub const DSA_OPCODE_DIF_UPDT: dsa_opcode = 21;
pub const DSA_OPCODE_DIX_GEN: dsa_opcode = 23;
pub const DSA_OPCODE_CFLUSH: dsa_opcode = 32;
#[allow(non_camel_case_types)]
pub type dsa_opcode = ::std::os::raw::c_uint;
pub const DSA_COMP_NONE: dsa_completion_status = 0;
pub const DSA_COMP_SUCCESS: dsa_completion_status = 1;
pub const DSA_COMP_SUCCESS_PRED: dsa_completion_status = 2;
pub const DSA_COMP_PAGE_FAULT_NOBOF: dsa_completion_status = 3;
pub const DSA_COMP_PAGE_FAULT_IR: dsa_completion_status = 4;
pub const DSA_COMP_BATCH_FAIL: dsa_completion_status = 5;
pub const DSA_COMP_BATCH_PAGE_FAULT: dsa_completion_status = 6;
pub const DSA_COMP_DR_OFFSET_NOINC: dsa_completion_status = 7;
pub const DSA_COMP_DR_OFFSET_ERANGE: dsa_completion_status = 8;
pub const DSA_COMP_DIF_ERR: dsa_completion_status = 9;
pub const DSA_COMP_BAD_OPCODE: dsa_completion_status = 16;
pub const DSA_COMP_INVALID_FLAGS: dsa_completion_status = 17;
pub const DSA_COMP_NOZERO_RESERVE: dsa_completion_status = 18;
pub const DSA_COMP_XFER_ERANGE: dsa_completion_status = 19;
pub const DSA_COMP_DESC_CNT_ERANGE: dsa_completion_status = 20;
pub const DSA_COMP_DR_ERANGE: dsa_completion_status = 21;
pub const DSA_COMP_OVERLAP_BUFFERS: dsa_completion_status = 22;
pub const DSA_COMP_DCAST_ERR: dsa_completion_status = 23;
pub const DSA_COMP_DESCLIST_ALIGN: dsa_completion_status = 24;
pub const DSA_COMP_INT_HANDLE_INVAL: dsa_completion_status = 25;
pub const DSA_COMP_CRA_XLAT: dsa_completion_status = 26;
pub const DSA_COMP_CRA_ALIGN: dsa_completion_status = 27;
pub const DSA_COMP_ADDR_ALIGN: dsa_completion_status = 28;
pub const DSA_COMP_PRIV_BAD: dsa_completion_status = 29;
pub const DSA_COMP_TRAFFIC_CLASS_CONF: dsa_completion_status = 30;
pub const DSA_COMP_PFAULT_RDBA: dsa_completion_status = 31;
pub const DSA_COMP_HW_ERR1: dsa_completion_status = 32;
pub const DSA_COMP_HW_ERR_DRB: dsa_completion_status = 33;
pub const DSA_COMP_TRANSLATION_FAIL: dsa_completion_status = 34;
pub const DSA_COMP_DRAIN_EVL: dsa_completion_status = 38;
pub const DSA_COMP_BATCH_EVL_ERR: dsa_completion_status = 39;
#[allow(non_camel_case_types)]
pub type dsa_completion_status = ::std::os::raw::c_uint;
#[repr(C, packed)]
#[derive(Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_hw_desc {
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 8usize]>,
    pub completion_addr: u64,
    pub __bindgen_anon_1: dsa_hw_desc__bindgen_ty_1,
    pub __bindgen_anon_2: dsa_hw_desc__bindgen_ty_2,
    pub __bindgen_anon_3: dsa_hw_desc__bindgen_ty_3,
    pub int_handle: u16,
    pub rsvd1: u16,
    pub __bindgen_anon_4: dsa_hw_desc__bindgen_ty_4,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union dsa_hw_desc__bindgen_ty_1 {
    pub src_addr: u64,
    pub rdback_addr: u64,
    pub pattern: u64,
    pub desc_list_addr: u64,
    pub pattern_lower: u64,
    pub transl_fetch_addr: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_1"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_1>() - 8usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_1"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_1>() - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_1::src_addr"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_1, src_addr) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_1::rdback_addr"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_1, rdback_addr) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_1::pattern"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_1, pattern) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_1::desc_list_addr"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_1, desc_list_addr) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_1::pattern_lower"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_1, pattern_lower) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_1::transl_fetch_addr"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_1, transl_fetch_addr) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union dsa_hw_desc__bindgen_ty_2 {
    pub dst_addr: u64,
    pub rdback_addr2: u64,
    pub src2_addr: u64,
    pub comp_pattern: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_2"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_2>() - 8usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_2"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_2>() - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_2::dst_addr"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_2, dst_addr) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_2::rdback_addr2"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_2, rdback_addr2) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_2::src2_addr"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_2, src2_addr) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_2::comp_pattern"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_2, comp_pattern) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union dsa_hw_desc__bindgen_ty_3 {
    pub xfer_size: u32,
    pub desc_count: u32,
    pub region_size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_3"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_3>() - 4usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_3"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_3>() - 4usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_3::xfer_size"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_3, xfer_size) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_3::desc_count"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_3, desc_count) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_3::region_size"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_3, region_size) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union dsa_hw_desc__bindgen_ty_4 {
    pub expected_res: u8,
    pub __bindgen_anon_1: dsa_hw_desc__bindgen_ty_4__bindgen_ty_1,
    pub delta_rec_size: u32,
    pub dest2: u64,
    pub __bindgen_anon_2: dsa_hw_desc__bindgen_ty_4__bindgen_ty_2,
    pub __bindgen_anon_3: dsa_hw_desc__bindgen_ty_4__bindgen_ty_3,
    pub __bindgen_anon_4: dsa_hw_desc__bindgen_ty_4__bindgen_ty_4,
    pub __bindgen_anon_5: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5,
    pub pattern_upper: u64,
    pub __bindgen_anon_6: dsa_hw_desc__bindgen_ty_4__bindgen_ty_6,
    pub __bindgen_anon_7: dsa_hw_desc__bindgen_ty_4__bindgen_ty_7,
    pub op_specific: [u8; 24usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_hw_desc__bindgen_ty_4__bindgen_ty_1 {
    pub delta_addr: u64,
    pub max_delta_size: u32,
    pub delt_rsvd: u32,
    pub expected_res_mask: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_4__bindgen_ty_1"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_1>() - 24usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_4__bindgen_ty_1"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_1>() - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_1::delta_addr"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_1, delta_addr) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_1::max_delta_size"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_1, max_delta_size) - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_1::delt_rsvd"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_1, delt_rsvd) - 12usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_1::expected_res_mask"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_1,
        expected_res_mask
    ) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_hw_desc__bindgen_ty_4__bindgen_ty_2 {
    pub crc_seed: u32,
    pub crc_rsvd: u32,
    pub seed_addr: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_4__bindgen_ty_2"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_2>() - 16usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_4__bindgen_ty_2"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_2>() - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_2::crc_seed"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_2, crc_seed) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_2::crc_rsvd"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_2, crc_rsvd) - 4usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_2::seed_addr"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_2, seed_addr) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_hw_desc__bindgen_ty_4__bindgen_ty_3 {
    pub src_dif_flags: u8,
    pub dif_chk_res: u8,
    pub dif_chk_flags: u8,
    pub dif_chk_res2: [u8; 5usize],
    pub chk_ref_tag_seed: u32,
    pub chk_app_tag_mask: u16,
    pub chk_app_tag_seed: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_4__bindgen_ty_3"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_3>() - 16usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_4__bindgen_ty_3"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_3>() - 4usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_3::src_dif_flags"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_3, src_dif_flags) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_3::dif_chk_res"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_3, dif_chk_res) - 1usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_3::dif_chk_flags"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_3, dif_chk_flags) - 2usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_3::dif_chk_res2"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_3, dif_chk_res2) - 3usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_3::chk_ref_tag_seed"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_3,
        chk_ref_tag_seed
    ) - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_3::chk_app_tag_mask"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_3,
        chk_app_tag_mask
    ) - 12usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_3::chk_app_tag_seed"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_3,
        chk_app_tag_seed
    ) - 14usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_hw_desc__bindgen_ty_4__bindgen_ty_4 {
    pub dif_ins_res: u8,
    pub dest_dif_flag: u8,
    pub dif_ins_flags: u8,
    pub dif_ins_res2: [u8; 13usize],
    pub ins_ref_tag_seed: u32,
    pub ins_app_tag_mask: u16,
    pub ins_app_tag_seed: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_4__bindgen_ty_4"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_4>() - 24usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_4__bindgen_ty_4"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_4>() - 4usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_4::dif_ins_res"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_4, dif_ins_res) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_4::dest_dif_flag"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_4, dest_dif_flag) - 1usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_4::dif_ins_flags"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_4, dif_ins_flags) - 2usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_4::dif_ins_res2"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_4, dif_ins_res2) - 3usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_4::ins_ref_tag_seed"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_4,
        ins_ref_tag_seed
    ) - 16usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_4::ins_app_tag_mask"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_4,
        ins_app_tag_mask
    ) - 20usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_4::ins_app_tag_seed"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_4,
        ins_app_tag_seed
    ) - 22usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_hw_desc__bindgen_ty_4__bindgen_ty_5 {
    pub src_upd_flags: u8,
    pub upd_dest_flags: u8,
    pub dif_upd_flags: u8,
    pub dif_upd_res: [u8; 5usize],
    pub src_ref_tag_seed: u32,
    pub src_app_tag_mask: u16,
    pub src_app_tag_seed: u16,
    pub dest_ref_tag_seed: u32,
    pub dest_app_tag_mask: u16,
    pub dest_app_tag_seed: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_4__bindgen_ty_5"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_5>() - 24usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_4__bindgen_ty_5"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_5>() - 4usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::src_upd_flags"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_5, src_upd_flags) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::upd_dest_flags"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_5, upd_dest_flags) - 1usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::dif_upd_flags"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_5, dif_upd_flags) - 2usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::dif_upd_res"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_5, dif_upd_res) - 3usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::src_ref_tag_seed"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_5,
        src_ref_tag_seed
    ) - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::src_app_tag_mask"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_5,
        src_app_tag_mask
    ) - 12usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::src_app_tag_seed"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_5,
        src_app_tag_seed
    ) - 14usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::dest_ref_tag_seed"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_5,
        dest_ref_tag_seed
    ) - 16usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::dest_app_tag_mask"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_5,
        dest_app_tag_mask
    ) - 20usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_5::dest_app_tag_seed"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_5,
        dest_app_tag_seed
    ) - 22usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_hw_desc__bindgen_ty_4__bindgen_ty_6 {
    pub transl_fetch_res: u64,
    pub region_stride: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_4__bindgen_ty_6"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_6>() - 16usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_4__bindgen_ty_6"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_6>() - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_6::transl_fetch_res"][::std::mem::offset_of!(
        dsa_hw_desc__bindgen_ty_4__bindgen_ty_6,
        transl_fetch_res
    ) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_6::region_stride"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_6, region_stride) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_hw_desc__bindgen_ty_4__bindgen_ty_7 {
    pub dix_gen_res: u8,
    pub dest_dif_flags: u8,
    pub dif_flags: u8,
    pub dix_gen_res2: [u8; 13usize],
    pub ref_tag_seed: u32,
    pub app_tag_mask: u16,
    pub app_tag_seed: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_4__bindgen_ty_7"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_7>() - 24usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_4__bindgen_ty_7"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_4__bindgen_ty_7>() - 4usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_7::dix_gen_res"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_7, dix_gen_res) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_7::dest_dif_flags"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_7, dest_dif_flags) - 1usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_7::dif_flags"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_7, dif_flags) - 2usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_7::dix_gen_res2"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_7, dix_gen_res2) - 3usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_7::ref_tag_seed"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_7, ref_tag_seed) - 16usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_7::app_tag_mask"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_7, app_tag_mask) - 20usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4__bindgen_ty_7::app_tag_seed"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4__bindgen_ty_7, app_tag_seed) - 22usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc__bindgen_ty_4"]
        [::std::mem::size_of::<dsa_hw_desc__bindgen_ty_4>() - 24usize];
    ["Alignment of dsa_hw_desc__bindgen_ty_4"]
        [::std::mem::align_of::<dsa_hw_desc__bindgen_ty_4>() - 8usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4::expected_res"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4, expected_res) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4::delta_rec_size"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4, delta_rec_size) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4::dest2"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4, dest2) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4::pattern_upper"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4, pattern_upper) - 0usize];
    ["Offset of field: dsa_hw_desc__bindgen_ty_4::op_specific"]
        [::std::mem::offset_of!(dsa_hw_desc__bindgen_ty_4, op_specific) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_hw_desc"][::std::mem::size_of::<dsa_hw_desc>() - 64usize];
    ["Alignment of dsa_hw_desc"][::std::mem::align_of::<dsa_hw_desc>() - 1usize];
    ["Offset of field: dsa_hw_desc::completion_addr"]
        [::std::mem::offset_of!(dsa_hw_desc, completion_addr) - 8usize];
    ["Offset of field: dsa_hw_desc::int_handle"]
        [::std::mem::offset_of!(dsa_hw_desc, int_handle) - 36usize];
    ["Offset of field: dsa_hw_desc::rsvd1"][::std::mem::offset_of!(dsa_hw_desc, rsvd1) - 38usize];
};
impl dsa_hw_desc {
    pub fn new() -> Self {
        Self {
            _bitfield_align_1: [0; 0],
            _bitfield_1: __BindgenBitfieldUnit::new([0; 8]),
            completion_addr: 0,
            __bindgen_anon_1: dsa_hw_desc__bindgen_ty_1 { src_addr: 0 },
            __bindgen_anon_2: dsa_hw_desc__bindgen_ty_2 { dst_addr: 0 },
            __bindgen_anon_3: dsa_hw_desc__bindgen_ty_3 { xfer_size: 0 },
            int_handle: 0,
            rsvd1: 0,
            __bindgen_anon_4: dsa_hw_desc__bindgen_ty_4 { expected_res: 0 },
        }
    }
    #[inline]
    pub fn pasid(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 20u8) as u32) }
    }
    #[inline]
    pub fn set_pasid(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 20u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn pasid_raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                20u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_pasid_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                20u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn rsvd(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(20usize, 11u8) as u32) }
    }
    #[inline]
    pub fn set_rsvd(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(20usize, 11u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn rsvd_raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                20usize,
                11u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_rsvd_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                20usize,
                11u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn priv_(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(31usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_priv(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(31usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn priv_raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                31usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_priv_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                31usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn flags(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(32usize, 24u8) as u32) }
    }
    #[inline]
    pub fn set_flags(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(32usize, 24u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn flags_raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                32usize,
                24u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_flags_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                32usize,
                24u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn opcode(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(56usize, 8u8) as u32) }
    }
    #[inline]
    pub fn set_opcode(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(56usize, 8u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn opcode_raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                56usize,
                8u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_opcode_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                56usize,
                8u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        pasid: u32,
        rsvd: u32,
        priv_: u32,
        flags: u32,
        opcode: u32,
    ) -> __BindgenBitfieldUnit<[u8; 8usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 8usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 20u8, {
            let pasid: u32 = unsafe { ::std::mem::transmute(pasid) };
            pasid as u64
        });
        __bindgen_bitfield_unit.set(20usize, 11u8, {
            let rsvd: u32 = unsafe { ::std::mem::transmute(rsvd) };
            rsvd as u64
        });
        __bindgen_bitfield_unit.set(31usize, 1u8, {
            let priv_: u32 = unsafe { ::std::mem::transmute(priv_) };
            priv_ as u64
        });
        __bindgen_bitfield_unit.set(32usize, 24u8, {
            let flags: u32 = unsafe { ::std::mem::transmute(flags) };
            flags as u64
        });
        __bindgen_bitfield_unit.set(56usize, 8u8, {
            let opcode: u32 = unsafe { ::std::mem::transmute(opcode) };
            opcode as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_raw_desc {
    pub field: [u64; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_raw_desc"][::std::mem::size_of::<dsa_raw_desc>() - 64usize];
    ["Alignment of dsa_raw_desc"][::std::mem::align_of::<dsa_raw_desc>() - 1usize];
    ["Offset of field: dsa_raw_desc::field"][::std::mem::offset_of!(dsa_raw_desc, field) - 0usize];
};
#[repr(C, packed)]
#[derive(Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_completion_record {
    pub status: u8,
    pub __bindgen_anon_1: dsa_completion_record__bindgen_ty_1,
    pub fault_info: u8,
    pub rsvd: u8,
    pub __bindgen_anon_2: dsa_completion_record__bindgen_ty_2,
    pub fault_addr: u64,
    pub __bindgen_anon_3: dsa_completion_record__bindgen_ty_3,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union dsa_completion_record__bindgen_ty_1 {
    pub result: u8,
    pub dif_status: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record__bindgen_ty_1"]
        [::std::mem::size_of::<dsa_completion_record__bindgen_ty_1>() - 1usize];
    ["Alignment of dsa_completion_record__bindgen_ty_1"]
        [::std::mem::align_of::<dsa_completion_record__bindgen_ty_1>() - 1usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_1::result"]
        [::std::mem::offset_of!(dsa_completion_record__bindgen_ty_1, result) - 0usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_1::dif_status"]
        [::std::mem::offset_of!(dsa_completion_record__bindgen_ty_1, dif_status) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union dsa_completion_record__bindgen_ty_2 {
    pub bytes_completed: u32,
    pub descs_completed: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record__bindgen_ty_2"]
        [::std::mem::size_of::<dsa_completion_record__bindgen_ty_2>() - 4usize];
    ["Alignment of dsa_completion_record__bindgen_ty_2"]
        [::std::mem::align_of::<dsa_completion_record__bindgen_ty_2>() - 4usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_2::bytes_completed"]
        [::std::mem::offset_of!(dsa_completion_record__bindgen_ty_2, bytes_completed) - 0usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_2::descs_completed"]
        [::std::mem::offset_of!(dsa_completion_record__bindgen_ty_2, descs_completed) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union dsa_completion_record__bindgen_ty_3 {
    pub __bindgen_anon_1: dsa_completion_record__bindgen_ty_3__bindgen_ty_1,
    pub delta_rec_size: u32,
    pub crc_val: u64,
    pub __bindgen_anon_2: dsa_completion_record__bindgen_ty_3__bindgen_ty_2,
    pub __bindgen_anon_3: dsa_completion_record__bindgen_ty_3__bindgen_ty_3,
    pub __bindgen_anon_4: dsa_completion_record__bindgen_ty_3__bindgen_ty_4,
    pub __bindgen_anon_5: dsa_completion_record__bindgen_ty_3__bindgen_ty_5,
    pub op_specific: [u8; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_completion_record__bindgen_ty_3__bindgen_ty_1 {
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record__bindgen_ty_3__bindgen_ty_1"]
        [::std::mem::size_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_1>() - 4usize];
    ["Alignment of dsa_completion_record__bindgen_ty_3__bindgen_ty_1"]
        [::std::mem::align_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_1>() - 4usize];
};
impl dsa_completion_record {
    pub fn new() -> Self {
        Self {
            status: 0,
            __bindgen_anon_1: dsa_completion_record__bindgen_ty_1 { result: 0 },
            fault_info: 0,
            rsvd: 0,
            __bindgen_anon_2: dsa_completion_record__bindgen_ty_2 { bytes_completed: 0 },
            fault_addr: 0,
            __bindgen_anon_3: dsa_completion_record__bindgen_ty_3 { delta_rec_size: 0 },
        }
    }
}
impl dsa_completion_record__bindgen_ty_3__bindgen_ty_1 {
    #[inline]
    pub fn invalid_flags(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 24u8) as u32) }
    }
    #[inline]
    pub fn set_invalid_flags(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 24u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn invalid_flags_raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                24u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_invalid_flags_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                24u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn rsvd2(&self) -> u32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(24usize, 8u8) as u32) }
    }
    #[inline]
    pub fn set_rsvd2(&mut self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(24usize, 8u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn rsvd2_raw(this: *const Self) -> u32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                24usize,
                8u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_rsvd2_raw(this: *mut Self, val: u32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                24usize,
                8u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(invalid_flags: u32, rsvd2: u32) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 24u8, {
            let invalid_flags: u32 = unsafe { ::std::mem::transmute(invalid_flags) };
            invalid_flags as u64
        });
        __bindgen_bitfield_unit.set(24usize, 8u8, {
            let rsvd2: u32 = unsafe { ::std::mem::transmute(rsvd2) };
            rsvd2 as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_completion_record__bindgen_ty_3__bindgen_ty_2 {
    pub dif_chk_ref_tag: u32,
    pub dif_chk_app_tag_mask: u16,
    pub dif_chk_app_tag: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record__bindgen_ty_3__bindgen_ty_2"]
        [::std::mem::size_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_2>() - 8usize];
    ["Alignment of dsa_completion_record__bindgen_ty_3__bindgen_ty_2"]
        [::std::mem::align_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_2>() - 4usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_2::dif_chk_ref_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_2,
        dif_chk_ref_tag
    )
        - 0usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_2::dif_chk_app_tag_mask"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_2,
        dif_chk_app_tag_mask
    )
        - 4usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_2::dif_chk_app_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_2,
        dif_chk_app_tag
    )
        - 6usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_completion_record__bindgen_ty_3__bindgen_ty_3 {
    pub dif_ins_res: u64,
    pub dif_ins_ref_tag: u32,
    pub dif_ins_app_tag_mask: u16,
    pub dif_ins_app_tag: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record__bindgen_ty_3__bindgen_ty_3"]
        [::std::mem::size_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_3>() - 16usize];
    ["Alignment of dsa_completion_record__bindgen_ty_3__bindgen_ty_3"]
        [::std::mem::align_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_3>() - 8usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_3::dif_ins_res"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_3,
        dif_ins_res
    ) - 0usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_3::dif_ins_ref_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_3,
        dif_ins_ref_tag
    )
        - 8usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_3::dif_ins_app_tag_mask"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_3,
        dif_ins_app_tag_mask
    )
        - 12usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_3::dif_ins_app_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_3,
        dif_ins_app_tag
    )
        - 14usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_completion_record__bindgen_ty_3__bindgen_ty_4 {
    pub dif_upd_src_ref_tag: u32,
    pub dif_upd_src_app_tag_mask: u16,
    pub dif_upd_src_app_tag: u16,
    pub dif_upd_dest_ref_tag: u32,
    pub dif_upd_dest_app_tag_mask: u16,
    pub dif_upd_dest_app_tag: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record__bindgen_ty_3__bindgen_ty_4"]
        [::std::mem::size_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_4>() - 16usize];
    ["Alignment of dsa_completion_record__bindgen_ty_3__bindgen_ty_4"]
        [::std::mem::align_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_4>() - 4usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_4::dif_upd_src_ref_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_4,
        dif_upd_src_ref_tag
    )
        - 0usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_4::dif_upd_src_app_tag_mask"] [:: std :: mem :: offset_of ! (dsa_completion_record__bindgen_ty_3__bindgen_ty_4 , dif_upd_src_app_tag_mask) - 4usize] ;
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_4::dif_upd_src_app_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_4,
        dif_upd_src_app_tag
    )
        - 6usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_4::dif_upd_dest_ref_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_4,
        dif_upd_dest_ref_tag
    )
        - 8usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_4::dif_upd_dest_app_tag_mask"] [:: std :: mem :: offset_of ! (dsa_completion_record__bindgen_ty_3__bindgen_ty_4 , dif_upd_dest_app_tag_mask) - 12usize] ;
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_4::dif_upd_dest_app_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_4,
        dif_upd_dest_app_tag
    )
        - 14usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_completion_record__bindgen_ty_3__bindgen_ty_5 {
    pub dix_gen_res: u64,
    pub dix_ref_tag: u32,
    pub dix_app_tag_mask: u16,
    pub dix_app_tag: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record__bindgen_ty_3__bindgen_ty_5"]
        [::std::mem::size_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_5>() - 16usize];
    ["Alignment of dsa_completion_record__bindgen_ty_3__bindgen_ty_5"]
        [::std::mem::align_of::<dsa_completion_record__bindgen_ty_3__bindgen_ty_5>() - 8usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_5::dix_gen_res"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_5,
        dix_gen_res
    ) - 0usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_5::dix_ref_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_5,
        dix_ref_tag
    ) - 8usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_5::dix_app_tag_mask"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_5,
        dix_app_tag_mask
    )
        - 12usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3__bindgen_ty_5::dix_app_tag"][::std::mem::offset_of!(
        dsa_completion_record__bindgen_ty_3__bindgen_ty_5,
        dix_app_tag
    )
        - 14usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record__bindgen_ty_3"]
        [::std::mem::size_of::<dsa_completion_record__bindgen_ty_3>() - 16usize];
    ["Alignment of dsa_completion_record__bindgen_ty_3"]
        [::std::mem::align_of::<dsa_completion_record__bindgen_ty_3>() - 8usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3::delta_rec_size"]
        [::std::mem::offset_of!(dsa_completion_record__bindgen_ty_3, delta_rec_size) - 0usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3::crc_val"]
        [::std::mem::offset_of!(dsa_completion_record__bindgen_ty_3, crc_val) - 0usize];
    ["Offset of field: dsa_completion_record__bindgen_ty_3::op_specific"]
        [::std::mem::offset_of!(dsa_completion_record__bindgen_ty_3, op_specific) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_completion_record"][::std::mem::size_of::<dsa_completion_record>() - 32usize];
    ["Alignment of dsa_completion_record"]
        [::std::mem::align_of::<dsa_completion_record>() - 1usize];
    ["Offset of field: dsa_completion_record::status"]
        [::std::mem::offset_of!(dsa_completion_record, status) - 0usize];
    ["Offset of field: dsa_completion_record::fault_info"]
        [::std::mem::offset_of!(dsa_completion_record, fault_info) - 2usize];
    ["Offset of field: dsa_completion_record::rsvd"]
        [::std::mem::offset_of!(dsa_completion_record, rsvd) - 3usize];
    ["Offset of field: dsa_completion_record::fault_addr"]
        [::std::mem::offset_of!(dsa_completion_record, fault_addr) - 8usize];
};
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
#[allow(non_camel_case_types)]
pub struct dsa_raw_completion_record {
    pub field: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dsa_raw_completion_record"]
        [::std::mem::size_of::<dsa_raw_completion_record>() - 32usize];
    ["Alignment of dsa_raw_completion_record"]
        [::std::mem::align_of::<dsa_raw_completion_record>() - 1usize];
    ["Offset of field: dsa_raw_completion_record::field"]
        [::std::mem::offset_of!(dsa_raw_completion_record, field) - 0usize];
};