FROM ubuntu:latest 

WORKDIR /root

RUN apt update && apt install -y libaccel-config-dev \
    libaccel-config1 libnuma-dev ssh python3 \
    python3-paramiko unzip wget ca-certificates curl gnupg

COPY dto/libdto.so.1.0 /usr/lib64/libdto.so.1.0
COPY sshev.py /root/sshev.py

RUN ln -sf /usr/lib64/libdto.so.1.0 /usr/lib64/libdto.so.1 && \
	ln -sf /usr/lib64/libdto.so.1.0 /usr/lib64/libdto.so