FROM ollama/ollama:0.10.0-rc1-rocm

ENV OLLAMA_MODELS=/root/models

WORKDIR /root

RUN apt update && apt install -y libaccel-config-dev \
    libaccel-config1 libnuma-dev

COPY dto/libdto.so.1.0 /usr/lib64/libdto.so.1.0

RUN ln -sf /usr/lib64/libdto.so.1.0 /usr/lib64/libdto.so.1 && \
	ln -sf /usr/lib64/libdto.so.1.0 /usr/lib64/libdto.so