FROM ubuntu:latest

WORKDIR /root

RUN apt update && apt install -y libaccel-config-dev \
    libaccel-config1 libnuma-dev ssh python3 python3-paramiko

COPY dto/libdto.so.1.0 /usr/lib64/libdto.so.1.0

RUN ln -sf /usr/lib64/libdto.so.1.0 /usr/lib64/libdto.so.1 && \
	ln -sf /usr/lib64/libdto.so.1.0 /usr/lib64/libdto.so